export { provinceRoutes } from "./province.route";
export { regencyRoutes } from "./regency.route";
export { districtRoutes } from "./district.route";
export { villageRoutes } from "./village.route";
export { authRoutes } from "./auth.route";
export { cacheRoutes } from "./cache.route";
export { unitPelaksanaanTeknisRoutes } from "./unit-pelaksanaan-teknis.route";
export { roleRoutes } from "./role.route";
export { organisasiRoutes } from "./organisasi.route";
export { pegawaiRoute as pegawaiRoutes } from "./pegawai.route";
export { kelompokNelayanRoute as kelompokNelayanRoutes } from "./kelompok-nelayan.route";
export { penyuluhRoute as penyuluhRoutes } from "./penyuluh.route";
